# Generated by Django 5.2.5 on 2025-09-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('report_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'project_table',
                'managed': True,
            },
        ),
    ]
