# Generated by Django 5.2.5 on 2025-09-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
