# Generated by Django 5.2.5 on 2025-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0002_alter_project_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
