# Generated by Django 5.2.5 on 2025-09-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0003_alter_project_report_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_contact', models.CharField(max_length=255, null=True)),
                ('report_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('report_quantity_per_employee', models.IntegerField(default=0)),
                ('employee_role', models.CharField(max_length=120, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('templates_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Location',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='write_data.client'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='write_data.client')),
            ],
            options={
                'db_table': 'Template',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_type', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_types', to='write_data.template')),
            ],
            options={
                'db_table': 'WaterType',
                'managed': True,
            },
        ),
    ]
