# Generated by Django 5.2.5 on 2025-09-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0005_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_contact',
            field=models.IntegerField(null=True),
        ),
    ]
