# Generated by Django 5.2.5 on 2025-09-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0006_alter_client_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
