# Generated by Django 5.2.5 on 2025-09-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0007_alter_client_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='write_data.location'),
            preserve_default=False,
        ),
    ]
