# Generated by Django 5.2.5 on 2025-09-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0008_template_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='template_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
