# Generated by Django 5.2.5 on 2025-09-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0009_client_template_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='templates_quantity',
            new_name='template_quantity',
        ),
    ]
