# Generated by Django 5.2.5 on 2025-09-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write_data', '0010_rename_templates_quantity_location_template_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='template_quantity',
            new_name='client_template_quantity',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='template_quantity',
            new_name='location_template_quantity',
        ),
    ]
