# Generated by Django 5.2.5 on 2025-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('report_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'reporters',
                'managed': True,
            },
        ),
    ]
