SELECT * FROM Sample_Tests st
INNER JOIN Samples s ON st.ClientSampleID = s.ClientSampleID
WHERE st.SampleTestsID = 1851951;

SELECT * FROM Sample_Tests WHERE SampleTestsID = 1851951;





SELECT * FROM Samples WHERE LabSampleID LIKE  '2509017-023 MB';

BEGIN TRANSACTION

BEGIN TRY

	UPDATE Sample_Tests SET LabSampleID = '2509019-026', ClientSampleID = '2509019-026 MSD'
	WHERE  SampleTestsID = 1851954;

	-- IF OK
	COMMIT TRANSACTION;
	PRINT 'TRANSACCIÓN COMPLETADA';

END TRY
BEGIN CATCH
	-- IF ERROR
	ROLLBACK TRANSACTION;
	PRINT 'Error: ' + ERROR_MESSAGE();
END CATCH